### ISSUE TITLE
bug: xattrs not being tracked

### ISSUE THREAD

**Issue by luna-xenia** [edera-dev/krata#118]
### What happened?

In krataoci-squashify, xattrs are not being tracked.

For example, with the image registry.gitlab.com/xenia-group/images/gnome-arch:main, the file `/usr/bin/newuidmap` will have the permissions -rwxr-xr-x when it should have -rws--x--x.

### Version / Commit

v0.0.9

**Comment by kaniini** [comment]
Technically the SUID bit is not an xattr, but you are likely correct that both SUID and xattrs aren't being tracked fully.  We need to add that information to the VFS in order to ensure they make it to the squashfs.

**Comment by azenla** [comment]
I looked into this and realized that the tar library we use doesn't support all PAX extensions. I'm sort of at my wits end on tar libraries in Rust, especially since we need async support. It's all a mess, and we may have to innovate to make this possible.
