### ISSUE TITLE
chore: documentation on custom kernels

### ISSUE THREAD

**Issue by andrewrynhard** [edera-dev/krata#119]
Hello,

I am interested in testing krata for use as a runtime for running [Talos Linux](https://github.com/siderolabs/talos) in Kubernetes. Talos has some unique requirements around the kernel it runs and I was hoping krata could eventually support running custom kernels.

**Comment by azenla** [comment]
Hello! There isn't actually much documentation on this yet, but there will be next week. krata supports custom kernels already ;)

If you package a kernel into a single OCI image layer with a file named "kernel" and launch with --kernel IMAGE_NAME it will use the kernel from the OCI image.

The PCI PR that is in the works brings support for modules and firmware to this system, and next week we will start publishing all supported kernel versions publicly.

I will provide an update for you once those features are shipped and documented!

**Comment by andrewrynhard** [comment]
> Hello! There isn't actually much documentation on this yet, but there will be next week. krata supports custom kernels already ;)
> 
> If you package a kernel into a single OCI image layer with a file named "kernel" and launch with --kernel IMAGE_NAME it will use the kernel from the OCI image.
> 
> The PCI PR that is in the works brings support for modules and firmware to this system, and next week we will start publishing all supported kernel versions publicly.
> 
> I will provide an update for you once those features are shipped and documented!

Awesome ... I need to do some work to see if krata will work with Talos. I will see if I can land official support for it in Talos.  Looking forward to seeing the docs!

**Comment by andrewrynhard** [comment]
Do you have office hours I might be able to attend and ask some questions?

**Comment by azenla** [comment]
@andrewrynhard Not at the moment (we will work on getting that setup soon) However, if you email us at contact@edera.dev we can do some 1:1 sessions if you’d like :)

**Comment by azenla** [comment]
> Do you have office hours I might be able to attend and ask some questions?

Hello! Wanted to let you know that I now have official office hours! https://calendar.app.google/cigZ8pRjgGEVYSwT7
