### ISSUE TITLE
bug: unable to find required guest file: addons.squashfs

### ISSUE THREAD

**Issue by gthvn1** [edera-dev/krata#125]
### What happened?

It seems that now you need to copy `./target/kernel/addons-x86_64.squashfs` into `/var/lib/krata/guest/addons.squashfs` so krata daemon will detect it. So maybe update the [point 7](https://github.com/edera-dev/krata/blob/84920a88ababecf054c6c70ed88e4c9d5110d4c2/DEV.md?plain=1#L71) of the development guide.

### Version / Commit

84920a88ababecf054c6c70ed88e4c9d5110d4c2

### Relevant log output

```shell
$ ./hack/debug/kratad.sh
    Finished release [optimized] target(s) in 0.72s
    Finished dev [unoptimized + debuginfo] target(s) in 0.75s
Error: unable to find required guest file: addons.squashfs
```
```

**Comment by azenla** [comment]
We can get this fixed today, thanks for the report!
