### ISSUE TITLE
feature: dynamic resource allocation

### ISSUE THREAD

**Issue by azenla** [edera-dev/krata#298]
We have always planned to support CPU and memory hot plugging, but it has not been implemented thus far. CPU hot plugging is probably not as critical, but memory hot plugging is extremely critical. This feature should include RPCs to update target resources, and also include reporting of actually consumed resources (for example, memory ballooning is a suggestion, not a requirement to the OS. It is under no obligation to return memory to the host).

**Comment by kaniini** [comment]
From the hypervisor side, it looks like we just have to use `XEN_DOMCTL_max_mem` hypercall to increase the allocation limit.  The limit must be page-aligned (e.g. 4KB granules, or 16KB granules on Apple Silicon).

This is the general procedure:

1. Write the new memory limit to the Xenstore under `memory/target`.  This triggers the domU to return current memory to the hypervisor.
2. Call `XEN_DOMCTL_max_mem` to adjust the memory limit.
3. Write the new memory limit to the `memory/static-max` leaf.  This triggers the domU to ask for new memory.

**Comment by kaniini** [comment]
Closed by 87530ed.
