### ISSUE TITLE
feature: exec tty support

### ISSUE THREAD

**Issue by azenla** [edera-dev/krata#335]
Right now, exec doesn't implement tty support. We should implement a tty flag and pass that through the stack, and let the exec handler allocate a tty.

**Comment by jedsalazar** [comment]
Not sure if I should put this here but I'm seeing terminal weirdness with attach, even after a `reset`

```
demo@bronze:~$ kubectl attach -it privileged
If you don't see a command prompt, try pressing enter.
^@
# ^@
# ^@
# ^@g^@r^@e^@p^@ ^@C^@a^@p^@ ^@/^@p^@r^@o^@c^@/^@1
```

**Comment by azenla** [comment]
> Not sure if I should put this here but I'm seeing terminal weirdness with attach, even after a `reset`
> 
> ```
> demo@bronze:~$ kubectl attach -it privileged
> If you don't see a command prompt, try pressing enter.
> ^@
> # ^@
> # ^@
> # ^@g^@r^@e^@p^@ ^@C^@a^@p^@ ^@/^@p^@r^@o^@c^@/^@1
> ```
> 
> The above is the output of
> 
> ```
> grep Cap /proc/1/
> ```

Hmm, I think this is due to terminal disagreement (IE control codes getting sent), will fix this in a follow up task.

**Comment by azenla** [comment]
Completed!
