### ISSUE TITLE
feature: guest metrics support

### ISSUE THREAD

**Issue by azenla** [edera-dev/krata#47]
Implement the ability to read metrics from the guest via the control service.

**Comment by kaniini** [comment]
Or maybe we make it more generic, where a MetricsItem can have `children`, which can be other MetricsItems.

For example, we could imagine a Guest -> Process(pid=Init) [guest.children[0]] -> Process(pid=busybox) [guest.children[0].children[0]].

**Comment by azenla** [comment]
Hmm, I think the MetricsItem approach is probably ideal, since this has to go into protobuf. I'm going to implement that strategy.
