### ISSUE TITLE
feature: provide feedback when converting large OCI images to squashfs

### ISSUE THREAD

**Issue by kaniini** [edera-dev/krata#50]
`kratactl launch -a cgr.dev/chainguard/powershell` for example can take several minutes on the first run as it imports the image and converts it to squashfs.

It would be nice to provide some feedback for the larger images as they are ingested.

**Comment by kaniini** [comment]
With #64 in this is fairly close, we just need to polish it a little.  For example, download status should use human-friendly suffixes for the progress indication.

**Comment by azenla** [comment]
@kaniini I think the latest functionality in #70 should be much more viable. We sped up squashing by using mksquashfs if available, and OCI progress feedback is now much cleaner, and I fixed a few progress bugs.
