### ISSUE TITLE
feature: security labels for guests

### ISSUE THREAD

**Issue by kaniini** [edera-dev/krata#63]
In order to allow for more expressive security policies, Flask-style (as seen in SELinux/TrustedBSD/Solaris) security labels should be applicable to guests, including default-inherited ones set by the hypervisor.

**Comment by kaniini** [comment]
Xen's take on this was XSM for what it's worth, but XSM is horrid for other reasons

**Comment by DemiMarie** [comment]
@kaniini want to dump a list of those reasons?
