### ISSUE TITLE
bug: krataoci-squashify not preserving setuid bit

### ISSUE THREAD

**Issue by luna-xenia** [edera-dev/krata#69]
On an arch based image:

``` 
$ podman run -it --entrypoint=/bin/bash registry.gitlab.com/xenia-group/images/templates/arch-image:main
[root@782eb26dccb3 img]# ls -lah /usr/bin/sudo
-rwsr-xr-x 1 root root 264K Dec 30 18:51 /usr/bin/sudo
[root@782eb26dccb3 img]# 
```

In the squashfs generated by krata:

```
$ sudo mount 51c3dd858cb9199a6237a0255b52f9d36ee339eac80ada5adb6c7b8158fa3225.squashfs /tmp/kmnt/
$ cd /tmp/kmnt/
$ ls -lah usr/bin/sudo
-rwxr-xr-x 1 root root 264K Dec 30 18:51 usr/bin/sudo
```

Seems like the setuid bit is being removed?

**Comment by azenla** [comment]
I will see if we can fix this very soon, I might need support from @wcampbell0x2a's library for it, a quick check says it doesn't support this.

**Comment by azenla** [comment]
For this use case, we have enabled use of mksquashfs if installed. Give that a try @luna-xenia (once the PR #70 is merged)

**Comment by wcampbell0x2a** [comment]
> I will see if we can fix this very soon, I might need support from @wcampbell0x2a's library for it, a quick check says it doesn't support this.

Pardon my ignorance, but isn't this part of the of the permissions u16 of squashfs?

**Comment by azenla** [comment]
> > I will see if we can fix this very soon, I might need support from @wcampbell0x2a's library for it, a quick check says it doesn't support this.
> 
> Pardon my ignorance, but isn't this part of the of the permissions u16 of squashfs?

You are right, it is actually. I am reworking lots of our OCI backend, so I should be able to add support for the right stuff now.

It turns out the problem was that the permissions bits weren't being preserved from the tar :)

**Comment by wcampbell0x2a** [comment]
> > > I will see if we can fix this very soon, I might need support from @wcampbell0x2a's library for it, a quick check says it doesn't support this.
> > 
> > 
> > Pardon my ignorance, but isn't this part of the of the permissions u16 of squashfs?
> 
> You are right, it is actually. I am reworking lots of our OCI backend, so I should be able to add support for the right stuff now.
> 
> It turns out the problem was that the permissions bits weren't being preserved from the tar :)

Sweet!
